### ISSUE TITLE
Task list formatting

### ISSUE THREAD

**Issue by txtyash** [remarkjs/remark-language-server#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Task list is incorrectly formatted. Brackets are escaped during formatting.

### Solution

No need to escape brackets while formatting task list.

### Alternatives

-

**Comment by wooorm** [comment]
Please don't open 3 issues. Spend time framing your question. jeez

**Comment by txtyash** [comment]
@wooorm 
The task list should look like this:
```md
- [ ] Artificial Intelligence
  - [ ] Unit III **Adversarial Search and Games**
  - [ ] Unit IV **Knowledge**
  - [ ] Unit V **Reasoning**
  - [ ] Unit VI **Planning**
  - [ ] Prelim Questions
```
but on saving the file it looks like:
```md
*   \[ ] Artificial Intelligence
    *   \[ ] Unit III **Adversarial Search and Games**
    *   \[ ] Unit IV **Knowledge**
    *   \[ ] Unit V **Reasoning**
    *   \[ ] Unit VI **Planning**
    *   \[ ] Prelim Questions
```

**Comment by wooorm** [comment]
Stop spamming or I will block you.

Follow our support guide to ask for help.

Use `remark-gfm`.
